### ISSUE TITLE
Hospitality: Map Gen incompatibility with Save Our Ship 2

### ISSUE THREAD

**Issue by brucethemoose** [OrionFive/Hospitality#579] opened 2021-08-15 23:10 UTC
**Describe the bug**
Save Our Ship 2 just added a new "Afterlife Vault" scenario. Trying to generate a map with this scenario bugs out the pawns, as they aren't holograms like they're supposed to be, and prints out a Hospitality related error in the log.

I would bet this has something to do with the new hologram-related pawn code in SoS2.

**To Reproduce**
1. Load Rimworld with Save our Ship 2 and Hospitality, in that order.
2. Start a new map with the "Afterlife Vault" scenario.
3. The error occurs when the map is generated.

**Console log**
https://gist.github.com/HugsLibRecordKeeper/565484f5e715f5ced947b68a2c4f8b03#file-output_log-txt-L380-L389

**Comment by OrionFive** [comment] 2021-08-16 09:41
The problem is that when the scenario starts it's killing pawns before the map is fully created with breaks an assumption Hospitality is making.

Should be fixed next version. Thanks for reporting this.

**Closed as completed by OrionFive** 2021-08-16 09:41 UTC
Labels: bug

**Comment by brucethemoose** [comment] 2021-08-16 16:39
Excellent! Thanks for developing Hospitality!
