### ISSUE TITLE
Gastronomy : pawn stuck in place 

### ISSUE THREAD

**Issue by Ayner964** [OrionFive/Hospitality#795] opened 2024-04-22 12:59 UTC
Everytime a pawn is waiting for restaurant work, they froze in place, wherever they may be on the map

**Console log**
https://gist.github.com/HugsLibRecordKeeper/430573cc10d7e38aeb156fcb09ac9909

**Screenshot**
![image](https://github.com/OrionFive/Hospitality/assets/167775570/950def63-23a0-4672-8f5d-9e68d384e0cc)

![image](https://github.com/OrionFive/Hospitality/assets/167775570/45980539-5782-45ce-be25-d5bbe1483ac8)

**Comment by OrionFive** [comment] 2024-04-23 06:15
Hmm. That's strange. No related errors in your log. Are you sure you made the log after the problem happened?

**Comment by Ayner964** [comment] 2024-04-23 12:14
It happen everytime. For all the pawn who are in the planning for the restaurant.
I made the log during the problem. 
It’s not a major bug but it’s inconvenient when they froze in place outside the base when it’s cold or when there is danger.

**Comment by OrionFive** [comment] 2024-04-23 14:48
That wasn't my first question. When did you create the log? Before or after it happened?

**Comment by Ayner964** [comment] 2024-04-23 16:54
It would be after then I guess.

**Comment by OrionFive** [comment] 2024-04-24 05:58
In that case I can't help you, because there's nothing in there that would suggest it's a bug. Is the pawn allowed to go where he should be?

**Comment by Ayner964** [comment] 2024-04-24 08:38
Yes he can, but don’t bother if it can’t be detected.
It’s not a real problem (like i can live with it)

**Comment by OrionFive** [comment] 2024-04-24 10:46
Then I really don't know, sorry. I'm gonna leave the issue open in case someone else can provide more information or can make it reproducible for us.

**Comment by Ayner964** [comment] 2024-04-24 11:57
Don’t worry, thanks for trying

**Comment by OrionFive** [comment] 2024-05-04 10:24
Found the issue. Thanks to Daisuke for providing a simple savegame to reproduce it with.
It's fixed in the next version.

**Closed as completed by OrionFive** 2024-05-04 10:24 UTC
Labels: bug, need more information

**Comment by Ayner964** [comment] 2024-05-04 12:20
Thanks a lot !
