### ISSUE TITLE
Hospitality: Offending Empire Royals

### ISSUE THREAD

**Issue by ryan-garmeson** [OrionFive/Hospitality#738] opened 2023-03-01 22:13 UTC
**Describe the bug**
Tried to entertain a visiting noble. Noble was offended every time, despite 15+ social on entertainer.

**To Reproduce**
1. Spawn Empire visitors
2. (hopefully one is high-ranked, I've only seen it with Baron+) Entertain / make friendships

**Console log**
Could not get link, bad request error. Here it is on my github ig: 
https://github.com/ryan-garmeson/logfiles/blob/cd5d7730e781134cb894dcde5aaddc368f8ab7c7/rimworld20230301

**Error stacktrace**
There is no logged error.

**Screenshots**
If you think it helps, add screenshots to help explain the problem.

Fixing bugs takes a lot of time. Please consider [becoming a patron](https://www.patreon.com/orionmods) to support development.

**Comment by ryan-garmeson** [comment] 2023-03-01 22:14
To be clear this is with Vanilla Empire Expanded.

**Comment by OrionFive** [comment] 2023-03-02 07:26
Thanks for the log. I'll see what I can do.

Unfortunately, there's no obvious cause.

**Comment by tvandyck** [comment] 2023-03-03 17:06
Just a guess. From a quick look in the code recruitmentResistanceOffset plays a role in charming/pleasing too, not just recruiting? 
And recruitmentResistanceOffset are insane high on those pawns 90-100. Which I think just overrides whatever negotiationskill you have.

**Comment by tomvd** [comment] 2023-03-03 20:55
An archduchess came along and I could entertain her after this fix(see PR). She had recruitmentResistanceOffset of 100. I did not try, but I don't think she could ever be recruited. But with a social skill of 15, you should be able -with some luck- to be able to entertain her from time to time.

**Comment by OrionFive** [comment] 2023-03-04 06:38
Yeah, not being able to recruit them is by design, because it breaks the whole Royalty gameplay if you can just skip the queue.

I haven't looked at the code for a while, but if I remember correctly, nobles have to be entertained by nobles, or they'll be pretty hard to please.

**Comment by tomvd** [comment] 2023-03-04 08:02
Oh, that makes sense. I am rather new in the whole royalty/empire idead. But it does make a lot of sense that people with honor are harder to entertain by "lower class riff-raff" - not matter how well they can speak.
So @ryan-garmeson what was the rank of the entertainer, that is the question. Not how much social skill he has :)

**Comment by OrionFive** [comment] 2023-03-04 14:40
There is a point, here, though, and that is that this mechanic isn't communicated to the player. So probably ranked guests should have a memory that explains why they were offended, or something else.
This isn't obviously to players.

**Comment by OrionFive** [comment] 2023-03-06 12:34
@tomvd I've looked into this. Your fix was correct. At some point, RimWorld must have changed the offset from values like 0.1 to values like 100.
I've pushed a fix.

**Closed as completed by OrionFive** 2023-03-06 12:34 UTC
Labels: bug
