### ISSUE TITLE
Not sure if it's a hospitality issue

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [OrionFive/Hospitality#192] opened 2018-11-04 11:26 UTC
But check out this log, bruv!

https://hastebin.com/ujanihoxip.txt
https://hastebin.com/xacugodidu.txt

Reaching the max message log limit in coupla seconds.

**Comment by OrionFive** [comment] 2018-11-04 11:44
Looks fancy, although I think it's a psychology issue / conflict. I'll investigate when I have more time again.
Any idea how I can reproduce it?

**Comment by rw-chaos** [comment] 2018-11-04 14:39
I have also psychology  installed and it's so far working fine together.

**Comment by OrionFive** [comment] 2018-11-15 09:12
Sorry. I can't reproduce this. And how do you know psychology is working fine? You're getting hundreds of errors...

**Comment by OrionFive** [comment] 2018-11-19 08:43
This is fixed now. It's caused by androids or similar pawns, which I obviously didn't test with.

**Closed as completed by OrionFive** 2018-11-19 08:43 UTC
