### ISSUE TITLE
Hospitality: Problem while loading; Object reference not set

### ISSUE THREAD

**Issue by Deggial2** [OrionFive/Hospitality#763] opened 2023-08-16 15:18 UTC
**Describe the bug**
What happened?

**To Reproduce**
1. Load the game ...
2. The bug's consequence: Beds can not be assigned to guests. Unsubscribing and then re-assigning again (forcing a reloading of all assets) unfortunately did not help! :( 

**Console log**
[HugsLib][ERR] Hospitality caused an exception during LoadReloadInitialize: System.NullReferenceException: Object reference not set to an instance of an object
  at Hospitality.Hospitality_SpecialInjector.CreateGuestBedDefs (Verse.ThingDef[] bedDefs, RimWorld.CompProperties_Facility[] facilities) [0x0026a] in <93480f50dd2b4e948dcfc5ce761b6d6a>:0 
  at Hospitality.Hospitality_SpecialInjector.Inject () [0x000be] in <93480f50dd2b4e948dcfc5ce761b6d6a>:0 
  at Hospitality.HospitalityModBase.Initialize () [0x00000] in <93480f50dd2b4e948dcfc5ce761b6d6a>:0 
  at HugsLib.HugsLibController.LoadReloadInitialize () [0x0007c] in <4a46802aeab646ab99159f7eecb6b57e>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
HugsLib.Utils.ModLogger:ReportException (System.Exception,string,bool,string)
HugsLib.HugsLibController:LoadReloadInitialize ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

Thank you for your work!

**Comment by OrionFive** [comment] 2023-08-16 15:59
This is a duplicate of #762. Please check there for a potential solution.

**Closed as completed by OrionFive** 2023-08-16 15:59 UTC
Labels: bug, duplicate
