### ISSUE TITLE
10jobs1tick

### ISSUE THREAD

**Issue by Daniel-USA** [OrionFive/Hospitality#82] opened 2017-06-17 05:28 UTC
https://gist.github.com/e73fd0b4fda01a179bffba2aa98832d9

pawn tries to mingle with teenager.

**Comment by OrionFive** [comment] 2017-06-17 10:44
I'm aware of this one (I'm getting it too). But I don't know how to fix it. 

I should probably get help from someone who understands the job system better.

**Comment by OrionFive** [comment] 2017-06-29 07:52
This is a duplicate of [https://github.com/OrionFive/Hospitality/issues/79](issue 79).

**Closed by OrionFive** 2017-06-29 07:52 UTC
